version = 1

[server]
url          = "http://127.0.0.1"
bind_address = "127.0.0.1"
port         = 8080

[database]
uri = "postgres://username:password@127.0.0.1/idp"

[cache]
uri       = "redis://127.0.0.1"
