services:
  postgres:
    image: postgres:16.4
    restart: "no"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=idp
  keydb:
    image: eqalpha/keydb:latest
    restart: "no"
    ports:
      - 6379:6379
    volumes:
      - keydb:/data

volumes:
  postgres:
  keydb:
