[formatting]
align_comments = true
align_entries  = true
indent_entries = false
reorder_keys   = false
reorder_arrays = true

[[rule]]
include = ["**/Cargo.toml"]
keys    = ["dependencies"]

[rule.formatting]
reorder_keys = true
