[package]
name    = "idp-state"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm.workspace   = true
fred.workspace      = true
thiserror.workspace = true
idp-config          = { path = "../idp-config" }
