[package]
name    = "idp-models"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm.workspace = true
argon2            = { version = "0.5.3", features = ["std"] }
chrono            = "0.4.38"
cuid2             = "0.1.2"
rand              = "0.8.5"
