[package]
name    = "idp-extractors"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace     = true
thiserror.workspace = true
axum                = "0.7.5"
mime = "0.3.17"
serde_json = "1.0.128"
serde_path_to_error = "0.1.16"
bytes = "1.7.1"
